{
 "title": "信息域已满",
 "tags": [ "linux" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   { "name": "domain", "label": "Host", "query": { "query": "label_values(domain)" } }
  ]
 },
 "panels": [
  {
   "title": "快速 CPU / 内存 / 磁盘",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "仪表盘",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU忙",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 7, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{domain=\"$domain\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',domain=\"$domain\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{domain=\"$domain\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "使用的内存",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{domain=\"$domain\"} * 100) / node_memory_MemTotal_bytes{domain=\"$domain\"})"
    }
   ]
  },
  {
   "title": "5分系统负责",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 7, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{domain=\"$domain\"}) /  count(count(node_cpu_seconds_total{domain=\"$domain\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "15分钟服务",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 7, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{domain=\"$domain\"}) /  count(count(node_cpu_seconds_total{domain=\"$domain\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "使用的根 FS",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 7, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{domain=\"$domain\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{domain=\"$domain\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "SWAP 使用",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 7, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{domain=\"$domain\"} - node_memory_SwapFree_bytes{domain=\"$domain\"}) / (node_memory_SwapTotal_bytes{domain=\"$domain\"} )) * 100"
    }
   ]
  },
  {
   "title": "下载",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{domain=\"$domain\"} - node_boot_time_seconds{domain=\"$domain\"}"
    }
   ]
  },
  {
   "title": "CPU核数",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{domain=\"$domain\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "内存",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{domain=\"$domain\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{domain=\"$domain\"}"
    }
   ]
  },
  {
   "title": "RootFS 全部",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{domain=\"$domain\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": " CPU / 内存 / 网络 /磁盘 基础信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "基础cpu",
     "type": "graph",
     "description": "Basic CPU info",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "内存基础",
     "type": "graph",
     "description": "Basic memory usage",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{domain=\"$domain\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{domain=\"$domain\"} - node_memory_MemFree_bytes{domain=\"$domain\"} - (node_memory_Cached_bytes{domain=\"$domain\"} + node_memory_Buffers_bytes{domain=\"$domain\"} + node_memory_SReclaimable_bytes{domain=\"$domain\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{domain=\"$domain\"} + node_memory_Buffers_bytes{domain=\"$domain\"} + node_memory_SReclaimable_bytes{domain=\"$domain\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{domain=\"$domain\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{domain=\"$domain\"} - node_memory_SwapFree_bytes{domain=\"$domain\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "网络传输基本信息",
     "type": "graph",
     "description": "Basic network info per interface",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{domain=\"$domain\"}[$__rate_interval])*8",
       "legendFormat": "recv {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{domain=\"$domain\"}[$__rate_interval])*8",
       "legendFormat": "trans {{device}} "
      }
     ]
    },
    {
     "title": "使用磁盘基本信息",
     "type": "graph",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{domain=\"$domain\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{domain=\"$domain\",device!~'rootfs'})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU / 内存 / 网络 / 磁盘",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "percentage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode=\"system\",domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "System - Processes executing in kernel mode"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='user',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "User - Normal processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='nice',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Nice - Niced processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Idle - Waiting for something to happen"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='iowait',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Iowait - Waiting for I/O to complete"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='irq',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Irq - Servicing interrupts"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='softirq',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Softirq - Servicing softirqs"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='steal',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='guest',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
      }
     ]
    },
    {
     "title": "存储",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{domain=\"$domain\"} - node_memory_MemFree_bytes{domain=\"$domain\"} - node_memory_Buffers_bytes{domain=\"$domain\"} - node_memory_Cached_bytes{domain=\"$domain\"} - node_memory_Slab_bytes{domain=\"$domain\"} - node_memory_PageTables_bytes{domain=\"$domain\"} - node_memory_SwapCached_bytes{domain=\"$domain\"}",
       "legendFormat": "Apps - Memory used by user-space applications"
      },
      {
       "expr": "node_memory_PageTables_bytes{domain=\"$domain\"}",
       "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
      },
      {
       "expr": "node_memory_SwapCached_bytes{domain=\"$domain\"}",
       "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
      },
      {
       "expr": "node_memory_Slab_bytes{domain=\"$domain\"}",
       "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
      },
      {
       "expr": "node_memory_Cached_bytes{domain=\"$domain\"}",
       "legendFormat": "Cache - Parked file data (file content) cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{domain=\"$domain\"}",
       "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
      },
      {
       "expr": "node_memory_MemFree_bytes{domain=\"$domain\"}",
       "legendFormat": "Unused - Free memory unassigned"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{domain=\"$domain\"} - node_memory_SwapFree_bytes{domain=\"$domain\"})",
       "legendFormat": "Swap - Swap space used"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{domain=\"$domain\"}",
       "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
      }
     ]
    },
    {
     "title": "网络流量",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bps", "label": "bits out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{domain=\"$domain\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{domain=\"$domain\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "空间磁盘",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{domain=\"$domain\",device!~'rootfs'} - node_filesystem_avail_bytes{domain=\"$domain\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "磁盘 IOPS",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{domain=\"$domain\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{domain=\"$domain\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "I/O 使用读/写",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "Bps", "label": "bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{domain=\"$domain\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Successfully read bytes"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{domain=\"$domain\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Successfully written bytes"
      }
     ]
    },
    {
     "title": "I/O 利用率",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "percentunit", "label": "%util" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{domain=\"$domain\",device=~\"$diskdevices\"} [$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "内存 Meminfo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "内存活动/非活动",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_bytes{domain=\"$domain\"}",
       "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
      },
      {
       "expr": "node_memory_Active_bytes{domain=\"$domain\"}",
       "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
      }
     ]
    },
    {
     "title": "内存提交",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{domain=\"$domain\"}",
       "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
      },
      {
       "expr": "node_memory_CommitLimit_bytes{domain=\"$domain\"}",
       "legendFormat": "CommitLimit - Amount of  memory currently available to be allocated on the system"
      }
     ]
    },
    {
     "title": "内存活动/非活动详细信息",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_file_bytes{domain=\"$domain\"}",
       "legendFormat": "Inactive_file - File-backed memory on inactive LRU list"
      },
      {
       "expr": "node_memory_Inactive_anon_bytes{domain=\"$domain\"}",
       "legendFormat": "Inactive_anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)"
      },
      {
       "expr": "node_memory_Active_file_bytes{domain=\"$domain\"}",
       "legendFormat": "Active_file - File-backed memory on active LRU list"
      },
      {
       "expr": "node_memory_Active_anon_bytes{domain=\"$domain\"}",
       "legendFormat": "Active_anon - Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs"
      }
     ]
    },
    {
     "title": "内存回写和脏数据",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{domain=\"$domain\"}",
       "legendFormat": "Writeback - Memory which is actively being written back to disk"
      },
      {
       "expr": "node_memory_WritebackTmp_bytes{domain=\"$domain\"}",
       "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
      },
      {
       "expr": "node_memory_Dirty_bytes{domain=\"$domain\"}",
       "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
      }
     ]
    },
    {
     "title": "内存共享和映射",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Mapped_bytes{domain=\"$domain\"}",
       "legendFormat": "Mapped - Used memory in mapped pages files which have been mmaped, such as libraries"
      },
      {
       "expr": "node_memory_Shmem_bytes{domain=\"$domain\"}",
       "legendFormat": "Shmem - Used shared memory (shared between several processes, thus including RAM disks)"
      },
      {
       "expr": "node_memory_ShmemHugePages_bytes{domain=\"$domain\"}",
       "legendFormat": "ShmemHugePages - Memory used by shared memory (shmem) and tmpfs allocated  with huge pages"
      },
      {
       "expr": "node_memory_ShmemPmdMapped_bytes{domain=\"$domain\"}",
       "legendFormat": "ShmemPmdMapped - Ammount of shared (shmem/tmpfs) memory backed by huge pages"
      }
     ]
    },
    {
     "title": "内存板",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_SUnreclaim_bytes{domain=\"$domain\"}",
       "legendFormat": "SUnreclaim - Part of Slab, that cannot be reclaimed on memory pressure"
      },
      {
       "expr": "node_memory_SReclaimable_bytes{domain=\"$domain\"}",
       "legendFormat": "SReclaimable - Part of Slab, that might be reclaimed, such as caches"
      }
     ]
    },
    {
     "title": "内存 Vmalloc",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_VmallocChunk_bytes{domain=\"$domain\"}",
       "legendFormat": "VmallocChunk - Largest contigious block of vmalloc area which is free"
      },
      {
       "expr": "node_memory_VmallocTotal_bytes{domain=\"$domain\"}",
       "legendFormat": "VmallocTotal - Total size of vmalloc memory area"
      },
      {
       "expr": "node_memory_VmallocUsed_bytes{domain=\"$domain\"}",
       "legendFormat": "VmallocUsed - Amount of vmalloc area which is used"
      }
     ]
    },
    {
     "title": "内存 Bounce",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Bounce_bytes{domain=\"$domain\"}",
       "legendFormat": "Bounce - Memory used for block device bounce buffers"
      }
     ]
    },
    {
     "title": "内存 Anonymous",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_AnonHugePages_bytes{domain=\"$domain\"}",
       "legendFormat": "AnonHugePages - Memory in anonymous huge pages"
      },
      {
       "expr": "node_memory_AnonPages_bytes{domain=\"$domain\"}",
       "legendFormat": "AnonPages - Memory in user pages not backed by files"
      }
     ]
    },
    {
     "title": "内存 Kernel / CPU",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 110 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_KernelStack_bytes{domain=\"$domain\"}",
       "legendFormat": "KernelStack - Kernel memory stack. This is not reclaimable"
      },
      {
       "expr": "node_memory_Percpu_bytes{domain=\"$domain\"}",
       "legendFormat": "PerCPU - Per CPU memory allocated dynamically by loadable modules"
      }
     ]
    },
    {
     "title": "内存 HugePages Counter",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "short", "label": "pages" }
     ],
     "targets": [
      {
       "expr": "node_memory_HugePages_Free{domain=\"$domain\"}",
       "legendFormat": "HugePages_Free - Huge pages in the pool that are not yet allocated"
      },
      {
       "expr": "node_memory_HugePages_Rsvd{domain=\"$domain\"}",
       "legendFormat": "HugePages_Rsvd - Huge pages for which a commitment to allocate from the pool has been made, but no allocation has yet been made"
      },
      {
       "expr": "node_memory_HugePages_Surp{domain=\"$domain\"}",
       "legendFormat": "HugePages_Surp - Huge pages in the pool above the value in /proc/sys/vm/nr_hugepages"
      }
     ]
    },
    {
     "title": "内存 HugePages Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 120 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_HugePages_Total{domain=\"$domain\"}",
       "legendFormat": "HugePages - Total size of the pool of huge pages"
      },
      {
       "expr": "node_memory_Hugepagesize_bytes{domain=\"$domain\"}",
       "legendFormat": "Hugepagesize - Huge Page size"
      }
     ]
    },
    {
     "title": "内存直接映射",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 130 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_DirectMap1G_bytes{domain=\"$domain\"}",
       "legendFormat": "DirectMap1G - Amount of pages mapped as this size"
      },
      {
       "expr": "node_memory_DirectMap2M_bytes{domain=\"$domain\"}",
       "legendFormat": "DirectMap2M - Amount of pages mapped as this size"
      },
      {
       "expr": "node_memory_DirectMap4k_bytes{domain=\"$domain\"}",
       "legendFormat": "DirectMap4K - Amount of pages mapped as this size"
      }
     ]
    },
    {
     "title": "内存不可清除和 MLocked",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 130 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Unevictable_bytes{domain=\"$domain\"}",
       "legendFormat": "Unevictable - Amount of unevictable memory that can't be swapped out for a variety of reasons"
      },
      {
       "expr": "node_memory_Mlocked_bytes{domain=\"$domain\"}",
       "legendFormat": "MLocked - Size of pages locked to memory using the mlock() system call"
      }
     ]
    },
    {
     "title": "内存 NFS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 140 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_NFS_Unstable_bytes{domain=\"$domain\"}",
       "legendFormat": "NFS Unstable - Memory in NFS pages sent to the server, but not yet commited to the storage"
      }
     ]
    }
   ]
  },
  {
   "title": "内存 Vmstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "内存页 In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "pages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pgpgin{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "Pagesin - Page in operations"
      },
      {
       "expr": "rate(node_vmstat_pgpgout{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "Pagesout - Page out operations"
      }
     ]
    },
    {
     "title": "内存页 Swap In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "pages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pswpin{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "Pswpin - Pages swapped in"
      },
      {
       "expr": "rate(node_vmstat_pswpout{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "Pswpout - Pages swapped out"
      }
     ]
    },
    {
     "title": "内存页 Faults",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "faults" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pgfault{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "Pgfault - Page major and minor fault operations"
      },
      {
       "expr": "rate(node_vmstat_pgmajfault{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "Pgmajfault - Major page fault operations"
      },
      {
       "expr": "rate(node_vmstat_pgfault{domain=\"$domain\"}[$__rate_interval])  - rate(node_vmstat_pgmajfault{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "Pgminfault - Minor page fault operations"
      }
     ]
    },
    {
     "title": "OOM Killer",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_oom_kill{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "oom killer invocations "
      }
     ]
    }
   ]
  },
  {
   "title": "系统时间同步",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "时间同步漂移",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds{domain=\"$domain\"}",
       "legendFormat": "Estimated error in seconds"
      },
      {
       "expr": "node_timex_offset_seconds{domain=\"$domain\"}",
       "legendFormat": "Time offset in between local system and reference clock"
      },
      {
       "expr": "node_timex_maxerror_seconds{domain=\"$domain\"}",
       "legendFormat": "Maximum error in seconds"
      }
     ]
    },
    {
     "title": "时间 PLL 调整",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_timex_loop_time_constant{domain=\"$domain\"}",
       "legendFormat": "Phase-locked loop time adjust"
      }
     ]
    },
    {
     "title": "时间同步状态",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_timex_sync_status{domain=\"$domain\"}",
       "legendFormat": "Is clock synchronized to a reliable server (1 = yes, 0 = no)"
      },
      {
       "expr": "node_timex_frequency_adjustment_ratio{domain=\"$domain\"}",
       "legendFormat": "Local clock frequency adjustment"
      }
     ]
    },
    {
     "title": "时间杂项",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "node_timex_tick_seconds{domain=\"$domain\"}",
       "legendFormat": "Seconds between clock ticks"
      },
      {
       "expr": "node_timex_tai_offset_seconds{domain=\"$domain\"}",
       "legendFormat": "International Atomic Time (TAI) offset"
      }
     ]
    }
   ]
  },
  {
   "title": "系统进程",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "进程状态",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_procs_blocked{domain=\"$domain\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      },
      {
       "expr": "node_procs_running{domain=\"$domain\"}",
       "legendFormat": "Processes in runnable state"
      }
     ]
    },
    {
     "title": "进程状态",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_processes_state{domain=\"$domain\"}",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "进程分叉",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "forks / sec" }
     ],
     "targets": [
      {
       "expr": "rate(node_forks_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "Processes forks second"
      }
     ]
    },
    {
     "title": "进程内存",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "decbytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(process_virtual_memory_bytes{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "Processes virtual memory size in bytes"
      },
      {
       "expr": "process_resident_memory_max_bytes{domain=\"$domain\"}",
       "legendFormat": "Maximum amount of virtual memory available in bytes"
      },
      {
       "expr": "rate(process_virtual_memory_bytes{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "Processes virtual memory size in bytes"
      },
      {
       "expr": "rate(process_virtual_memory_max_bytes{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "Maximum amount of virtual memory available in bytes"
      }
     ]
    },
    {
     "title": "PID 数量和限制",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_processes_pids{domain=\"$domain\"}",
       "legendFormat": "Number of PIDs"
      },
      {
       "expr": "node_processes_max_processes{domain=\"$domain\"}",
       "legendFormat": "PIDs limit"
      }
     ]
    },
    {
     "title": "进程调度统计运行/等待",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "rate(node_schedstat_running_seconds_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
      },
      {
       "expr": "rate(node_schedstat_waiting_seconds_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
      }
     ]
    },
    {
     "title": "线程数和限制",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_processes_threads{domain=\"$domain\"}",
       "legendFormat": "Allocated threads"
      },
      {
       "expr": "node_processes_max_threads{domain=\"$domain\"}",
       "legendFormat": "Threads limit"
      }
     ]
    }
   ]
  },
  {
   "title": "系统杂项",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "上下文切换/中断",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_context_switches_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "Context switches"
      },
      {
       "expr": "rate(node_intr_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "Interrupts"
      }
     ]
    },
    {
     "title": "系统负载",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_load1{domain=\"$domain\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{domain=\"$domain\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{domain=\"$domain\"}",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "中断详情",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_interrupts_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{ type }} - {{ info }}"
      }
     ]
    },
    {
     "title": "调度每个cpu执行的时间片",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_schedstat_timeslices_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "CPU {{ cpu }}"
      }
     ]
    },
    {
     "title": "熵",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_entropy_available_bits{domain=\"$domain\"}",
       "legendFormat": "Entropy available to random number generators"
      }
     ]
    },
    {
     "title": "在用户和系统上下文中花费的 CPU 时间",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "Time spent"
      }
     ]
    },
    {
     "title": "文件描述符",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "process_max_fds{domain=\"$domain\"}",
       "legendFormat": "Maximum open file descriptors"
      },
      {
       "expr": "process_open_fds{domain=\"$domain\"}",
       "legendFormat": "Open file descriptors"
      }
     ]
    }
   ]
  },
  {
   "title": "硬件杂项",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "硬件温度监控",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "celsius", "label": "temperature" }
     ],
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius{domain=\"$domain\"}",
       "legendFormat": "{{ chip }} {{ sensor }} temp"
      },
      {
       "expr": "node_hwmon_temp_crit_celsius{domain=\"$domain\"}",
       "legendFormat": "{{ chip }} {{ sensor }} Critical"
      }
     ]
    },
    {
     "title": "节流冷却装置",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_cooling_device_cur_state{domain=\"$domain\"}",
       "legendFormat": "Current {{ name }} in {{ type }}"
      },
      {
       "expr": "node_cooling_device_max_state{domain=\"$domain\"}",
       "legendFormat": "Max {{ name }} in {{ type }}"
      }
     ]
    },
    {
     "title": "电源",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_power_supply_online{domain=\"$domain\"}",
       "legendFormat": "{{ power_supply }} online"
      }
     ]
    }
   ]
  },
  {
   "title": "Systemd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "系统套接字",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_systemd_socket_accepted_connections_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{ name }} Connections"
      }
     ]
    },
    {
     "title": "系统单位状态",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_systemd_units{domain=\"$domain\",state=\"activating\"}",
       "legendFormat": "Activating"
      },
      {
       "expr": "node_systemd_units{domain=\"$domain\",state=\"active\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_systemd_units{domain=\"$domain\",state=\"deactivating\"}",
       "legendFormat": "Deactivating"
      },
      {
       "expr": "node_systemd_units{domain=\"$domain\",state=\"failed\"}",
       "legendFormat": "Failed"
      },
      {
       "expr": "node_systemd_units{domain=\"$domain\",state=\"inactive\"}",
       "legendFormat": "Inactive"
      }
     ]
    }
   ]
  },
  {
   "title": "存储盘",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "磁盘 IOPS 已完成",
     "type": "graph",
     "description": "The number (after merges) of I/O requests completed per second for the device",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "磁盘读写数据",
     "type": "graph",
     "description": "The number of bytes read from or written to the device per second",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "Bps", "label": "bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read bytes"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Written bytes"
      }
     ]
    },
    {
     "title": "磁盘平均等待时间",
     "type": "graph",
     "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s", "label": "time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_time_seconds_total{domain=\"$domain\"}[$__rate_interval]) / rate(node_disk_reads_completed_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read wait time avg"
      },
      {
       "expr": "rate(node_disk_write_time_seconds_total{domain=\"$domain\"}[$__rate_interval]) / rate(node_disk_writes_completed_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write wait time avg"
      }
     ]
    },
    {
     "title": "平均队列大小",
     "type": "graph",
     "description": "The average queue length of the requests that were issued to the device",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "none", "label": "aqu-sz" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_weighted_seconds_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "磁盘读写合并",
     "type": "graph",
     "description": "The number of read and write requests merged per second that were queued to the device",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "iops", "label": "I/Os" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_merged_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read merged"
      },
      {
       "expr": "rate(node_disk_writes_merged_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write merged"
      }
     ]
    },
    {
     "title": "花在 I/O 上的时间",
     "type": "graph",
     "description": "Percentage of elapsed time during which I/O requests were issued to the device (bandwidth utilization for the device). Device saturation occurs when this value is close to 100% for devices serving requests serially.  But for devices  serving requests in parallel, such as RAID arrays and modern SSDs, this number does not reflect their performance limits.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "percentunit", "label": "%util" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - IO"
      },
      {
       "expr": "rate(node_disk_discard_time_seconds_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - discard"
      }
     ]
    },
    {
     "title": "瞬时队列大小",
     "type": "graph",
     "description": "The number of outstanding requests at the instant the sample was taken. Incremented as requests are given to appropriate struct request_queue and decremented as they finish.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "none", "label": "Outstanding req." }
     ],
     "targets": [
      {
       "expr": "node_disk_io_now{domain=\"$domain\"}",
       "legendFormat": "{{device}} - IO now"
      }
     ]
    },
    {
     "title": "完成/合并的磁盘 IOps 丢弃",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "iops", "label": "IOs" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_discards_completed_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Discards completed"
      },
      {
       "expr": "rate(node_disk_discards_merged_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Discards merged"
      }
     ]
    }
   ]
  },
  {
   "title": "存储文件系统",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "可用的文件系统空间",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{domain=\"$domain\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - Available"
      }
     ]
    },
    {
     "title": "文件节点免费",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "file nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files_free{domain=\"$domain\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - Free file nodes"
      }
     ]
    },
    {
     "title": "文件描述符",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "files" }
     ],
     "targets": [
      {
       "expr": "node_filefd_maximum{domain=\"$domain\"}",
       "legendFormat": "Max open files"
      },
      {
       "expr": "node_filefd_allocated{domain=\"$domain\"}",
       "legendFormat": "Open files"
      }
     ]
    },
    {
     "title": "文件节点大小",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "file Nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files{domain=\"$domain\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - File nodes total"
      }
     ]
    },
    {
     "title": "只读文件系统/错误",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_readonly{domain=\"$domain\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - ReadOnly"
      },
      {
       "expr": "node_filesystem_device_error{domain=\"$domain\",device!~'rootfs',fstype!~'tmpfs'}",
       "legendFormat": "{{mountpoint}} - Device error"
      }
     ]
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "数据包网络流量",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "rate(node_network_transmit_packets_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "网络流量错误",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_errs_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive errors"
      },
      {
       "expr": "rate(node_network_transmit_errs_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Rransmit errors"
      }
     ]
    },
    {
     "title": "网络流量下降",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_drop_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive drop"
      },
      {
       "expr": "rate(node_network_transmit_drop_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit drop"
      }
     ]
    },
    {
     "title": "网络流量压缩",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_compressed_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive compressed"
      },
      {
       "expr": "rate(node_network_transmit_compressed_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit compressed"
      }
     ]
    },
    {
     "title": "网络流量多播",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_multicast_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive multicast"
      }
     ]
    },
    {
     "title": "网络流量先进先出",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_fifo_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive fifo"
      },
      {
       "expr": "rate(node_network_transmit_fifo_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit fifo"
      }
     ]
    },
    {
     "title": "网络流量帧",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_frame_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive frame"
      }
     ]
    },
    {
     "title": "网络流量载体",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_carrier_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Statistic transmit_carrier"
      }
     ]
    },
    {
     "title": "网络流量调用",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_colls_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit colls"
      }
     ]
    },
    {
     "title": "NF合同",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "short", "label": "entries" }
     ],
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{domain=\"$domain\"}",
       "legendFormat": "NF conntrack entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{domain=\"$domain\"}",
       "legendFormat": "NF conntrack limit"
      }
     ]
    },
    {
     "title": "ARP 条目",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short", "label": "Entries" }
     ],
     "targets": [
      {
       "expr": "node_arp_entries{domain=\"$domain\"}",
       "legendFormat": "{{ device }} - ARP entries"
      }
     ]
    },
    {
     "title": "MTU",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_network_mtu_bytes{domain=\"$domain\"}",
       "legendFormat": "{{ device }} - Bytes"
      }
     ]
    },
    {
     "title": "速度",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_network_speed_bytes{domain=\"$domain\"}",
       "legendFormat": "{{ device }} - Speed"
      }
     ]
    },
    {
     "title": "队列长度",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "none", "label": "packets" }
     ],
     "targets": [
      {
       "expr": "node_network_transmit_queue_length{domain=\"$domain\"}",
       "legendFormat": "{{ device }} -   Interface transmit queue length"
      }
     ]
    },
    {
     "title": "软网封包",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
     "yaxes": [
      {
       "format": "short",
       "label": "packetes drop (-) / process (+)"
      }
     ],
     "targets": [
      {
       "expr": "rate(node_softnet_processed_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "CPU {{cpu}} - Processed"
      },
      {
       "expr": "rate(node_softnet_dropped_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "CPU {{cpu}} - Dropped"
      }
     ]
    },
    {
     "title": "软网超出配额",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_softnet_times_squeezed_total{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "CPU {{cpu}} - Squeezed"
      }
     ]
    },
    {
     "title": "网络运行状态",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_network_up{operstate=\"up\",domain=\"$domain\"}",
       "legendFormat": "{{interface}} - Operational state UP"
      },
      {
       "expr": "node_network_carrier{domain=\"$domain\"}",
       "legendFormat": "{{device}} - Physical link state"
      }
     ]
    }
   ]
  },
  {
   "title": "网络套接字",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "套接字TCP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{domain=\"$domain\"}",
       "legendFormat": "TCP_alloc - Allocated sockets"
      },
      {
       "expr": "node_sockstat_TCP_inuse{domain=\"$domain\"}",
       "legendFormat": "TCP_inuse - Tcp sockets currently in use"
      },
      {
       "expr": "node_sockstat_TCP_orphan{domain=\"$domain\"}",
       "legendFormat": "TCP_orphan - Orphan sockets"
      },
      {
       "expr": "node_sockstat_TCP_tw{domain=\"$domain\"}",
       "legendFormat": "TCP_tw - Sockets wating close"
      }
     ]
    },
    {
     "title": "套接字UDP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_UDPLITE_inuse{domain=\"$domain\"}",
       "legendFormat": "UDPLITE_inuse - Udplite sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_inuse{domain=\"$domain\"}",
       "legendFormat": "UDP_inuse - Udp sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_mem{domain=\"$domain\"}",
       "legendFormat": "UDP_mem - Used memory for udp"
      }
     ]
    },
    {
     "title": "Sockstat 碎片/原始",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_FRAG_inuse{domain=\"$domain\"}",
       "legendFormat": "FRAG_inuse - Frag sockets currently in use"
      },
      {
       "expr": "node_sockstat_RAW_inuse{domain=\"$domain\"}",
       "legendFormat": "RAW_inuse - Raw sockets currently in use"
      }
     ]
    },
    {
     "title": "Sockstat 内存大小",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_mem_bytes{domain=\"$domain\"}",
       "legendFormat": "mem_bytes - TCP sockets in that state"
      },
      {
       "expr": "node_sockstat_UDP_mem_bytes{domain=\"$domain\"}",
       "legendFormat": "mem_bytes - UDP sockets in that state"
      },
      {
       "expr": "node_sockstat_FRAG_memory{domain=\"$domain\"}",
       "legendFormat": "FRAG_memory - Used memory for frag"
      }
     ]
    },
    {
     "title": "使用的 Sockstat",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short", "label": "sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_sockets_used{domain=\"$domain\"}",
       "legendFormat": "Sockets_used - Sockets currently in use"
      }
     ]
    }
   ]
  },
  {
   "title": "网络统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Netstat IP 输入/输出八位字节",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "octects out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_IpExt_InOctets{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "InOctets - Received octets"
      },
      {
       "expr": "rate(node_netstat_IpExt_OutOctets{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "OutOctets - Sent octets"
      }
     ]
    },
    {
     "title": "Netstat IP 转发",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "datagrams" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Ip_Forwarding{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "Forwarding - IP forwarding"
      }
     ]
    },
    {
     "title": "ICMP 输入/输出",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Icmp_InMsgs{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
      },
      {
       "expr": "rate(node_netstat_Icmp_OutMsgs{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
      }
     ]
    },
    {
     "title": "ICMP 错误",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Icmp_InErrors{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
      }
     ]
    },
    {
     "title": "UDP 输入/输出",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short", "label": "datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Udp_InDatagrams{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "InDatagrams - Datagrams received"
      },
      {
       "expr": "rate(node_netstat_Udp_OutDatagrams{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "OutDatagrams - Datagrams sent"
      }
     ]
    },
    {
     "title": "UDP 错误",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short", "label": "datagrams" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Udp_InErrors{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "InErrors - UDP Datagrams that could not be delivered to an application"
      },
      {
       "expr": "rate(node_netstat_Udp_NoPorts{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener"
      },
      {
       "expr": "rate(node_netstat_UdpLite_InErrors{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "InErrors Lite - UDPLite Datagrams that could not be delivered to an application"
      },
      {
       "expr": "rate(node_netstat_Udp_RcvbufErrors{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "RcvbufErrors - UDP buffer errors received"
      },
      {
       "expr": "rate(node_netstat_Udp_SndbufErrors{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "SndbufErrors - UDP buffer errors send"
      }
     ]
    },
    {
     "title": "TCP 输入/输出",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short", "label": "datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_InSegs{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
      },
      {
       "expr": "rate(node_netstat_Tcp_OutSegs{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
      }
     ]
    },
    {
     "title": "TCP 错误",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_TcpExt_ListenOverflows{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
      },
      {
       "expr": "rate(node_netstat_TcpExt_ListenDrops{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
      },
      {
       "expr": "rate(node_netstat_TcpExt_TCPSynRetrans{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
      },
      {
       "expr": "rate(node_netstat_Tcp_RetransSegs{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
      },
      {
       "expr": "rate(node_netstat_Tcp_InErrs{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
      },
      {
       "expr": "rate(node_netstat_Tcp_OutRsts{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "OutRsts - Segments sent with RST flag"
      }
     ]
    },
    {
     "title": "TCP连接",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short", "label": "connections" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{domain=\"$domain\"}",
       "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
      },
      {
       "expr": "node_netstat_Tcp_MaxConn{domain=\"$domain\"}",
       "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dinamic is \"-1\")"
      }
     ]
    },
    {
     "title": "TCP SynCookie",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short", "label": "counter out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_TcpExt_SyncookiesFailed{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "SyncookiesFailed - Invalid SYN cookies received"
      },
      {
       "expr": "rate(node_netstat_TcpExt_SyncookiesRecv{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "SyncookiesRecv - SYN cookies received"
      },
      {
       "expr": "rate(node_netstat_TcpExt_SyncookiesSent{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "SyncookiesSent - SYN cookies sent"
      }
     ]
    },
    {
     "title": "TCP 直接转换",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short", "label": "connections" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_ActiveOpens{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
      },
      {
       "expr": "rate(node_netstat_Tcp_PassiveOpens{domain=\"$domain\"}[$__rate_interval])",
       "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
      }
     ]
    }
   ]
  },
  {
   "title": "节点导出器",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "节点导出器抓取时间",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{domain=\"$domain\"}",
       "legendFormat": "{{collector}} - Scrape duration"
      }
     ]
    },
    {
     "title": "节点出口Scrape",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_success{domain=\"$domain\"}",
       "legendFormat": "{{collector}} - Scrape success"
      },
      {
       "expr": "node_textfile_scrape_error{domain=\"$domain\"}",
       "legendFormat": "{{collector}} - Scrape textfile error (1 = true)"
      }
     ]
    }
   ]
  }
 ]
}