{
 "title": "管理程序",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "hypers", "label": "Hypervisors", "query": { "query": "label_values(hypervisor)" } },
   {
    "name": "domain",
    "label": "Host",
    "query": {
     "query": "label_values(isardvdi_hypervisor_scrape_duration_success{hypervisor=\"$hypers\"}, domain)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "仪表盘",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$hypers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "hypers",
   "collapsed": true,
   "panels": [
    { "title": "虚拟服务器状态 ", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 } },
    {
     "title": "系统负责",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_load1{domain=\"$domain\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{domain=\"$domain\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{domain=\"$domain\"}",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "percentage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode=\"system\",domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "System - Processes executing in kernel mode"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='user',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "User - Normal processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='nice',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Nice - Niced processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Idle - Waiting for something to happen"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='iowait',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Iowait - Waiting for I/O to complete"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='irq',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Irq - Servicing interrupts"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='softirq',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Softirq - Servicing softirqs"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='steal',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='guest',domain=\"$domain\"}[$__rate_interval])) * 100",
       "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
      }
     ]
    },
    {
     "title": "已使用磁盘",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{domain=\"$domain\",device!~'rootfs'} - node_filesystem_avail_bytes{domain=\"$domain\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "内存",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{domain=\"$domain\"} - node_memory_MemFree_bytes{domain=\"$domain\"} - node_memory_Buffers_bytes{domain=\"$domain\"} - node_memory_Cached_bytes{domain=\"$domain\"} - node_memory_Slab_bytes{domain=\"$domain\"} - node_memory_PageTables_bytes{domain=\"$domain\"} - node_memory_SwapCached_bytes{domain=\"$domain\"}",
       "legendFormat": "Apps - Memory used by user-space applications"
      },
      {
       "expr": "node_memory_PageTables_bytes{domain=\"$domain\"}",
       "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
      },
      {
       "expr": "node_memory_SwapCached_bytes{domain=\"$domain\"}",
       "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
      },
      {
       "expr": "node_memory_Slab_bytes{domain=\"$domain\"}",
       "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
      },
      {
       "expr": "node_memory_Cached_bytes{domain=\"$domain\"}",
       "legendFormat": "Cache - Parked file data (file content) cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{domain=\"$domain\"}",
       "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
      },
      {
       "expr": "node_memory_MemFree_bytes{domain=\"$domain\"}",
       "legendFormat": "Unused - Free memory unassigned"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{domain=\"$domain\"} - node_memory_SwapFree_bytes{domain=\"$domain\"})",
       "legendFormat": "Swap - Swap space used"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{domain=\"$domain\"}",
       "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
      }
     ]
    },
    {
     "title": "磁盘 IO",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{domain=\"$domain\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{domain=\"$domain\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "网络流量",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "bps", "label": "bits out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{domain=\"$domain\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{domain=\"$domain\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "I/O 利用率",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "percentunit", "label": "%util" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{domain=\"$domain\",device=~\"$diskdevices\"} [$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "I/O 使用 读 / 写",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "Bps", "label": "bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{domain=\"$domain\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Successfully read bytes"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{domain=\"$domain\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Successfully written bytes"
      }
     ]
    }
   ]
  }
 ]
}