{
 "title": "系统分类",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "hypers", "label": "Hypervisors", "query": { "query": "label_values(hypervisor)" } },
   {
    "name": "domain",
    "query": {
     "query": "label_values(isardvdi_hypervisor_scrape_duration_success{hypervisor=\"$hypers\"}, domain)"
    }
   },
   { "name": "category", "query": { "query": "label_values(category)" } },
   { "name": "group", "query": { "query": "label_values(group)" } }
  ]
 },
 "panels": [
  {
   "title": "仪表盘",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "全部桌面",
   "type": "stat",
   "description": "Total Desktops per categoria",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "isardvdi_isardvdi_api_desktop_number_category{category=\"$category\"}",
     "query": "from(bucket: \"isardvdi-go\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"isardvdi-api\")\n  |> filter(fn: (r) => r[\"_field\"] == \"desktops\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "全部用户",
   "type": "stat",
   "description": "Total Users per categoria",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_values by(role) (\"tipo\", isardvdi_isardvdi_api_user_info{category=\"$category\"}))",
     "query": "from(bucket: \"isardvdi-go\")\n  |> range(start: -100000000000000s)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"isardvdi-authentication\")\n  |> filter(fn: (r) => r[\"_field\"] == \"login\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> count(column: \"_value\")\n  |> unique(column: \"id\")\n  |> keep(columns: [\"_value\"])\n  |> count(column: \"_value\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "已启动桌面",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(isardvdi_domain_vcpu_current * on (desktop) label_replace(isardvdi_isardvdi_api_desktop_info * on (user) group_left label_replace(isardvdi_isardvdi_api_user_info{category=\"$category\"}, \"user\", \"$1\", \"id\", \"(.*)\"), \"desktop\", \"$1\", \"id\", \"(.*)\")) or vector(0)",
     "query": "from(bucket: \"isardvdi-go\")\n  |> range(start: -10s, stop: now())\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"domain\"\n  )\n  |> keep(columns: [\"_time\", \"id\"])\n  |> group()\n  |> unique(column: \"id\")\n  |> count(column: \"id\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "全部内存",
   "type": "stat",
   "description": "RAM memory per categoria",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(isardvdi_domain_mem_total * on (desktop) label_replace(isardvdi_isardvdi_api_desktop_info * on (user) group_left label_replace(isardvdi_isardvdi_api_user_info{category=\"$category\"}, \"user\", \"$1\", \"id\", \"(.*)\"), \"desktop\", \"$1\", \"id\", \"(.*)\")) "
    }
   ]
  },
  {
   "title": "按类别分类的用户",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values by(role) (\"categoria\", isardvdi_isardvdi_api_user_info{category=\"$category\"})",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "用户组",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values by(role) (\"categoria\", isardvdi_isardvdi_api_user_info{group=\"$group\"})",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "全部模板",
   "type": "stat",
   "description": "Total Templates per categoria",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "isardvdi_isardvdi_api_template_number_category{category=\"$category\"}",
     "query": "from(bucket: \"isardvdi-go\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"isardvdi-api\")\n  |> filter(fn: (r) => r[\"_field\"] == \"templates\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield()"
    }
   ]
  },
  {
   "title": "全部部署",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "isardvdi_isardvdi_api_deployment_number_category{category=\"$category\"}"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(isardvdi_domain_vcpu_current * on (desktop) label_replace(isardvdi_isardvdi_api_desktop_info * on (user) group_left label_replace(isardvdi_isardvdi_api_user_info{category=\"$category\"}, \"user\", \"$1\", \"id\", \"(.*)\"), \"desktop\", \"$1\", \"id\", \"(.*)\"))",
     "query": "from(bucket: \"isardvdi-go\")\n  |> range(start: -10s, stop: now())\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"domain\" and\n    r[\"hypervisor\"] == \"${hypers}\" and\n    r[\"_field\"] == \"vcpu_current\"\n  )\n  |> group(columns: [\"id\"])\n  |> sort(columns: [\"_time\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sum()"
    }
   ]
  },
  {
   "title": "桌面和模板",
   "type": "timeseries",
   "description": "Escriptoris i Plantilles per categoria",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "isardvdi_isardvdi_api_desktop_number_category{category=\"$category\"}",
     "legendFormat": "Escriptoris Creats",
     "query": " Desktops = from(bucket: \"isardvdi-go\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"domain\" \n  )\n  |> keep(columns: [\"_time\", \"id\"])\n  |> group()\n  |> aggregateWindow(every: 30s, column: \"id\", fn:(column, tables=<-) => tables \n    |> unique(column: column)\n    |> count(column:column),)\n  |> rename(columns: {id: \"_value\"})\n  |> map(fn: (r) => ({ Desktops:r._value, _time:r._time }))\n  |> yield()\nVisors = from(bucket: \"isardvdi-tasks\")\n  |> range(start: -10s, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hypervisor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"visors_started\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> map(fn: (r) => ({ Visors:r._value, _time:r._time  }))\n  |> yield(name: \"mean\")\n\n"
    },
    {
     "expr": "isardvdi_isardvdi_api_template_number_category{category=\"$category\"}",
     "legendFormat": "Plantilles Creades"
    }
   ]
  },
  {
   "title": "启动桌面",
   "type": "timeseries",
   "description": "Escriptoris Arrancats per categoria",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(isardvdi_domain_vcpu_current * on (desktop) label_replace(isardvdi_isardvdi_api_desktop_info * on (user) group_left label_replace(isardvdi_isardvdi_api_user_info{category=\"$category\"}, \"user\", \"$1\", \"id\", \"(.*)\"), \"desktop\", \"$1\", \"id\", \"(.*)\")) or vector(0)",
     "legendFormat": "Escriptoris"
    }
   ]
  },
  {
   "title": "总用户和类型",
   "type": "timeseries",
   "description": "Usuaris Totals i Tipus per categoria",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "CPU%",
     "expr": "sum(count_values by(role) (\"tipo\", isardvdi_isardvdi_api_user_info{category=\"$category\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Usuaris Totals",
     "measurement": "docker",
     "query": "SELECT mean(\"cpu_percent\") FROM \"$host.docker\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$container$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "expr": "count_values by(role) (\"categoria\", isardvdi_isardvdi_api_user_info{category=\"$category\"})",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "最近几个月的用户",
   "type": "timeseries",
   "description": "Usuaris dels últims mesos per categoria",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "CPU%",
     "expr": "sum(count_values by(role) (\"tipo\", count_over_time(isardvdi_isardvdi_api_user_info{category=\"$category\"}[60d]))) or vector(0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Usuaris dels últims mesos",
     "measurement": "docker",
     "query": "SELECT mean(\"cpu_percent\") FROM \"$host.docker\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$container$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "timeseries",
   "description": "vCPU per categoria",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(isardvdi_domain_vcpu_current * on (desktop) label_replace(isardvdi_isardvdi_api_desktop_info * on (user) group_left label_replace(isardvdi_isardvdi_api_user_info{category=\"$category\"}, \"user\", \"$1\", \"id\", \"(.*)\"), \"desktop\", \"$1\", \"id\", \"(.*)\")) or vector(0)",
     "legendFormat": "vCPU",
     "query": "from(bucket: \"isardvdi-go\")\n  |> range(start: -10s, stop: now())\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"domain\" and\n    r[\"hypervisor\"] == \"${hypers}\" and\n    r[\"_field\"] == \"vcpu_current\"\n  )\n  |> group(columns: [\"id\"])\n  |> sort(columns: [\"_time\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sum()"
    }
   ]
  },
  {
   "title": "全部内存",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(isardvdi_domain_mem_total * on (desktop) label_replace(isardvdi_isardvdi_api_desktop_info * on (user) group_left label_replace(isardvdi_isardvdi_api_user_info{category=\"$category\"}, \"user\", \"$1\", \"id\", \"(.*)\"), \"desktop\", \"$1\", \"id\", \"(.*)\")) or vector(0)"
    }
   ]
  }
 ]
}