{
 "title": "集群监控",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "hypers", "label": "Hypervisors", "query": { "query": "label_values(hypervisor)" } },
   { "name": "domain", "label": "Host", "query": { "query": "label_values(domain)" } },
   {
    "name": "id",
    "label": "id-hyper",
    "query": {
     "query": "label_values(isardvdi_isardvdi_api_hypervisor_info, id) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "仪表盘",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$id",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "isardvdi_isardvdi_api_hypervisor_info{id=\"$id\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "强制 $id",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "isardvdi_isardvdi_api_hypervisor_info{id=\"$id\"}",
     "legendFormat": "{{only_forced}}"
    }
   ]
  },
  { "title": "$domain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "domain" },
  {
   "title": "已启动桌面",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count_over_time(isardvdi_domain_vcpu_current{domain=~\"$domain\"}[1m]))",
     "query": "from(bucket: \"isardvdi-go\")\n  |> range(start: -10s, stop: now())\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"domain\" and\n    r[\"hypervisor\"] == \"${hypers}\"\n  )\n  |> keep(columns: [\"_time\", \"id\"])\n  |> group()\n  |> unique(column: \"id\")\n  |> count(column: \"id\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "启动桌面",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count by (desktop)(isardvdi_domain_vcpu_current{domain=~\"$domain\"})) or vector(0)",
     "legendFormat": "Escritorios",
     "query": " Desktops = from(bucket: \"isardvdi-go\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"domain\" \n  )\n  |> keep(columns: [\"_time\", \"id\"])\n  |> group()\n  |> aggregateWindow(every: 30s, column: \"id\", fn:(column, tables=<-) => tables \n    |> unique(column: column)\n    |> count(column:column),)\n  |> rename(columns: {id: \"_value\"})\n  |> map(fn: (r) => ({ Desktops:r._value, _time:r._time }))\n  |> yield()\nVisors = from(bucket: \"isardvdi-tasks\")\n  |> range(start: -10s, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hypervisor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"visors_started\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    |> map(fn: (r) => ({ Visors:r._value, _time:r._time  }))\n  |> yield(name: \"mean\")\n\n"
    }
   ]
  },
  {
   "title": "内存 %",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{domain=~\"$domain\"} * 100) / node_memory_MemTotal_bytes{domain=~\"$domain\"})"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "stat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{domain=~\"$domain\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',domain=~\"$domain\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{domain=~\"$domain\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "磁盘",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{domain=~\"$domain\", mountpoint=\"/opt/isard/groups\", fstype!=\"rootfs\"} * 100 / node_filesystem_size_bytes{domain=~\"$domain\", mountpoint=\"/opt/isard/groups\", fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "系统负载",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{domain=~\"$domain\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{domain=~\"$domain\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{domain=~\"$domain\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "蒙版启动",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(present_over_time(isardvdi_domain_port_spice_tls{domain=~\"$domain\"}[1m]) * on(desktop) group_left isardvdi_domain_port_spice_tls{domain=~\"$domain\"} * on (port,hypervisor) group_left count_over_time(isardvdi_socket_recv_bytes{domain=~\"$domain\"}[1m])) or vector(0))  + \n(count(present_over_time(isardvdi_domain_net_rx_bytes{domain=~\"$domain\"}[1m]) * on (mac) group_left count_over_time(isardvdi_conntrack_rdp_recv_bytes[1m])) or vector(0)) + (count(present_over_time(isardvdi_domain_port_vnc{domain=~\"$domain\"}[1m]) * on(desktop) group_left isardvdi_domain_port_vnc{domain=~\"$domain\"} * on (port, hypervisor) group_left count_over_time(isardvdi_socket_recv_bytes{domain=~\"$domain\"}[1m])) or vector(0))",
     "query": "from(bucket: \"isardvdi-tasks\")\n  |> range(start: -10s, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hypervisor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"visors_started\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}