{
 "title": "Rethinkdb数据库",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server_var", "label": "Server", "query": { "query": "label_values(server)" } },
   { "name": "db_var", "label": "Database", "query": { "query": "label_values(db)" } },
   {
    "name": "table_var",
    "label": "Table",
    "query": {
     "query": "label_values({db=~\"$db_var\"}, table)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "收集数据",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "仪表盘",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "统计收集持续时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "rethinkdb_scrape_latency", "legendFormat": "duration" }
   ]
  },
  {
   "title": "统计收集错误计数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rethinkdb_scrape_errors", "legendFormat": "errors count" }
   ]
  },
  {
   "title": "集群",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "每秒集群文档",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_cluster_docs_per_second",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "集群客户端连接",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_cluster_client_connections",
     "legendFormat": "connections count"
    }
   ]
  },
  {
   "title": "服务器",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "每秒服务器查询",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_server_queries_per_second{server=~\"$server_var\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "服务器文档每秒读取",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_server_docs_per_second{server=~\"$server_var\", operation=\"read\"}",
     "legendFormat": "{{server}}::{{operation}}"
    }
   ]
  },
  {
   "title": "服务器客户端连接",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_server_client_connections{server=~\"$server_var\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "每秒写入的服务器文档",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_server_docs_per_second{server=~\"$server_var\", operation=\"written\"}",
     "legendFormat": "{{server}}::{{operation}}"
    }
   ]
  },
  {
   "title": "数据库表",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "表文档每秒",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_table_docs_per_second{db=~\"$db_var\", table=~\"$table_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{operation}}"
    }
   ]
  },
  {
   "title": "每秒表副本 Docs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rethinkdb_tablereplica_docs_per_second{db=~\"$db_var\", table=~\"$table_var\", server=~\"$server_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{operation}}::{{server}}"
    }
   ]
  },
  {
   "title": "表副本磁盘 io 字节",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rethinkdb_tablereplica_io{db=~\"$db_var\", table=~\"$table_var\", server=~\"$server_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{operation}}::{{server}}"
    }
   ]
  },
  {
   "title": "表副本磁盘数据字节",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rethinkdb_tablereplica_data_bytes{db=~\"$db_var\", table=~\"$table_var\", server=~\"$server_var\"}",
     "legendFormat": "{{db}}.{{table}}::{{server}}"
    }
   ]
  }
 ]
}