{
 "title": "虚拟服务使用",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "hypers", "label": "Hypervisors", "query": { "query": "label_values(hypervisor)" } },
   { "name": "domain", "label": "Host", "query": { "query": "label_values(domain)" } }
  ]
 },
 "panels": [
  {
   "title": "仪表盘",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "/ 磁盘空间",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{domain=\"$domain\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{domain=\"$domain\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "$hypers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "hypers",
   "collapsed": true,
   "panels": [
    {
     "title": "按类别对用户进行排名",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(15, sort_desc(count_values by(category) (\"categoria\", isardvdi_isardvdi_api_user_info{domain=\"$domain\"})))",
       "legendFormat": "{{category}}"
      }
     ]
    },
    {
     "title": "按类别对模板进行排名",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(topk(15, isardvdi_isardvdi_api_template_number_category{domain=\"$domain\"}))",
       "legendFormat": "{{category}}"
      }
     ]
    },
    {
     "title": "按类别对桌面进行排名",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(topk(15, isardvdi_isardvdi_api_desktop_number_category{domain=\"$domain\"}))",
       "legendFormat": "{{category}}"
      }
     ]
    },
    {
     "title": "按类别分类的用户",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_values by(category) (\"categoria\", isardvdi_isardvdi_api_user_info{domain=\"$domain\"})",
       "legendFormat": "{{category}}"
      }
     ]
    },
    {
     "title": "按类别分类的模板",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "isardvdi_isardvdi_api_template_number_category{domain=\"$domain\"}",
       "legendFormat": "{{category}}"
      }
     ]
    },
    {
     "title": "按类别分类的桌面",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "isardvdi_isardvdi_api_desktop_number_category{domain=\"$domain\"}",
       "legendFormat": "{{category}}"
      }
     ]
    }
   ]
  }
 ]
}